server:
  port: 8081

spring:
  dubbo:
    application:
      name: provider-demo #应用名
    registry:
      address: zookeeper://192.168.162.131 #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20890 #dubbo服务暴露的端口
    scan: com.ylw.dubbo.provider.service #扫描的包名
